### ISSUE TITLE
Do we need to add "userId" to the DTO?

### ISSUE THREAD

**Issue by dennan141** [Erik-Ryman/Grupp-9-Kundprojekt-1#10]
```
// TODO: Do we need to add "userId" to the DTO?
```

https://github.com/Erik-Ryman/Grupp-9-Kundprojekt-1/blob/f18900b3762213c3e0f80e24b00e98dd85681347/Frontend/kundprojekt1-frontend/src/services/postService.ts#L20

**Comment by Erik-Ryman** [comment]
Fixat
