### ISSUE TITLE
Improve the admin controll

### ISSUE THREAD

**Issue by dennan141** [Erik-Ryman/Grupp-9-Kundprojekt-1#16]
```
		// TODO: Must be 1000 better ways to do this but works for now... 
```

https://github.com/Erik-Ryman/Grupp-9-Kundprojekt-1/blob/47698bcb9fb11d09161eb91cf212ff41aa551053/Frontend/kundprojekt1-frontend/src/stores/users.ts#L18

**Comment by Erik-Ryman** [comment]
Fixat
