### ISSUE TITLE
Logout func

### ISSUE THREAD

**Issue by dennan141** [Erik-Ryman/Grupp-9-Kundprojekt-1#23]
```
  //TODO: Logout func
```

https://github.com/Erik-Ryman/Grupp-9-Kundprojekt-1/blob/84cf89184152c4bfc6240f458517c7cd1a26d75e/Frontend/kundprojekt1-frontend/src/app/pages/profile/page.tsx#L12

**Comment by Erik-Ryman** [comment]
Fixat
